// <auto-generated />
using System;
using ApiProduct.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiProduct.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiProduct.Models.Product", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ID = new Guid("0dd8151c-5fdb-41a6-a6d7-21e30d6963ef"),
                            Description = "Laptop Dell XPS 13, 11ª Geração Intel Core i7, 16GB RAM, 512GB SSD",
                            Price = 8499.00m
                        },
                        new
                        {
                            ID = new Guid("abe2182a-c093-4571-b7f3-2abe1f09f3aa"),
                            Description = "Mouse Logitech MX Master 3, Wireless, 4000 DPI",
                            Price = 499.00m
                        },
                        new
                        {
                            ID = new Guid("2cce7a2a-5daa-4352-8aff-5a90bba52efb"),
                            Description = "Teclado Mecânico Corsair K95, RGB, Switch Cherry MX",
                            Price = 1199.00m
                        },
                        new
                        {
                            ID = new Guid("fd422584-3018-49a4-b8b0-de4813561a41"),
                            Description = "Monitor LG UltraWide 34'', WQHD, IPS, 75Hz",
                            Price = 3299.00m
                        },
                        new
                        {
                            ID = new Guid("99dd86c8-2643-4e67-88e7-5a649b5c950b"),
                            Description = "Headset Gamer HyperX Cloud II, Surround 7.1, USB",
                            Price = 799.00m
                        },
                        new
                        {
                            ID = new Guid("3e680e1d-0d18-44b9-98c0-b2dd7228c1f1"),
                            Description = "SSD Samsung 970 EVO Plus 1TB, NVMe M.2",
                            Price = 1199.00m
                        },
                        new
                        {
                            ID = new Guid("10507c9d-cf26-4d3d-963d-39f045ecf9f5"),
                            Description = "Placa de Vídeo NVIDIA GeForce RTX 3080, 10GB GDDR6X",
                            Price = 7499.00m
                        },
                        new
                        {
                            ID = new Guid("cfb63739-81d0-4efa-aed4-9fef9b06b62e"),
                            Description = "Impressora Multifuncional HP DeskJet 2776, Wi-Fi, Jato de Tinta",
                            Price = 499.00m
                        },
                        new
                        {
                            ID = new Guid("2af1a308-ec3a-4ad1-9fba-7137740e522d"),
                            Description = "Cadeira Gamer DXRacer Formula Series, Ergonomica",
                            Price = 1699.00m
                        },
                        new
                        {
                            ID = new Guid("ba3e3b61-5d20-4d3a-8787-be84b2a2ef66"),
                            Description = "Roteador Wi-Fi TP-Link Archer AX6000, Dual Band, 8 Antenas",
                            Price = 1299.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
